# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Terry Chan's Blog
description: > # this means to ignore newlines until "baseurl:"
  实验各种兴趣方案
baseurl: "/"
url: "https://www.terrychan.org/"
permalink: /post/:year-:month-:day-:title
# permalink: /post/:title
repository: ShawnTeoh/matjek
paginate: 10

# MatJek specific configurations
# github_profile: "https://github.com/napoler"
user: "Terry Chan"
user_email: ""
# contact_url: "https://github.com/napoler"
google_tracking_id: "UA-17239407-23"
google_site_verification: "UA-17239407-23"
disqus_shortname: "https-www-terrychan-org"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true

theme: jekyll-theme-cayman